### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by betatim**
Increase the version of `nbserverproxy` required as the previous version of it had a bug which prevents nbrsessionproxy from working.

### CODE REVIEW

**Comment by betatim** [comment]
This is the fix in nbserverproxy https://github.com/jupyterhub/nbserverproxy/pull/59

**Comment by betatim** [comment]
It would be great to also release a new version of nbrsessionproxy right after merging this. This is why I already icnreased the version number in `setup.py` of this package itself.

**Comment by ryanlovett** [comment]
Tagged, and made a new release.

**Comment by yuvipanda** [comment]
Thanks, @ryanlovett!

I also added @betatim and @minrk as owners on PyPI.

**Comment by betatim** [comment]
Whoop! 🎉

**Pull request merged**
